version: "3.5"

volumes:
    librenms:
        driver: local
    db:
        driver: local

networks:
  main:
  
services:
  librenms:
    image: librenms/librenms:latest
    container_name: pwd_librenms
    hostname: librenms
    networks:
      - main
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - librenms:/data
    environment:
      - "TZ=Europe/London"
      - "PUID=1001"
      - "PGID=1001"
      - "DB_HOST=db"
      - "DB_NAME=librenms"
      - "DB_USER=librenms"
      - "DB_PASSWORD=librenmsdemo"
      - "DB_TIMEOUT=30"
      - "UPLOAD_MAX_SIZE=16M"
      - "OPCACHE_MEM_SIZE=128"
      - "REAL_IP_FROM=0.0.0.0/32"
      - "REAL_IP_HEADER=X-Forwarded-For"
      - "LOG_IP_VAR=http_x_forwarded_for"
      - "LIBRENMS_POLLER_THREADS=16"
      - "LIBRENMS_POLLER_INTERVAL=5"
      - "LIBRENMS_CRON_DISCOVERY_ENABLE=true"
      - "LIBRENMS_CRON_DAILY_ENABLE=true"
      - "LIBRENMS_CRON_ALERTS_ENABLE=true"
      - "LIBRENMS_CRON_BILLING_ENABLE=true"
      - "LIBRENMS_CRON_BILLING_CALCULATE_ENABLE=true"
      - "LIBRENMS_CRON_CHECK_SERVICES_ENABLE=true"
      - "LIBRENMS_CRON_POLLER_ENABLE=true"
      - "LIBRENMS_SNMP_COMMUNITY=librenmsdocker"
      - "counttables=0"
    restart: unless-stopped

  db:
    image: mariadb:10.2
    container_name: pwd_librenms_db
    networks:
      - main
    command:
      - "mysqld"
      - "--sql-mode="
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - db:/var/lib/mysql
    environment:
      - "TZ=Europe/London"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=librenms"
      - "MYSQL_USER=librenms"
      - "MYSQL_PASSWORD=librenmsdemo"
    restart: always

  cron:
    image: librenms/librenms:latest
    container_name: pwd_librenms_cron
    hostname: librenms
    networks:
      - main
    volumes:
      - librenms:/data
    environment:
      - "TZ=Europe/London"
      - "PUID=1001"
      - "PGID=1001"
      - "DB_HOST=db"
      - "DB_NAME=librenms"
      - "DB_USER=librenms"
      - "DB_PASSWORD=librenmsdemo"
      - "DB_TIMEOUT=30"
      - "UPLOAD_MAX_SIZE=16M"
      - "OPCACHE_MEM_SIZE=128"
      - "REAL_IP_FROM=0.0.0.0/32"
      - "REAL_IP_HEADER=X-Forwarded-For"
      - "LOG_IP_VAR=http_x_forwarded_for"
      - "LIBRENMS_POLLER_THREADS=16"
      - "LIBRENMS_POLLER_INTERVAL=5"
      - "LIBRENMS_CRON_DISCOVERY_ENABLE=true"
      - "LIBRENMS_CRON_DAILY_ENABLE=true"
      - "LIBRENMS_CRON_ALERTS_ENABLE=true"
      - "LIBRENMS_CRON_BILLING_ENABLE=true"
      - "LIBRENMS_CRON_BILLING_CALCULATE_ENABLE=true"
      - "LIBRENMS_CRON_CHECK_SERVICES_ENABLE=true"
      - "LIBRENMS_CRON_POLLER_ENABLE=true"
      - "LIBRENMS_SNMP_COMMUNITY=librenmsdocker"
      - "MEMORY_LIMIT=256M"
      - "SIDECAR_CRON=1"
    restart: always
